security:
    encoders:
        US\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:   ^/(_(profiler|wdt|error)|css|images|js)/
            security:  false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: us_section_index
            logout:
                path:   fos_user_security_logout
                target: us_section_index
            remember_me:
                key:    %secret%

        default:
            anonymous: ~

    access_control:
        - { path: ^/manage/, roles: ROLE_ADMIN }
