# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_builder:
        class: US\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.manage_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu_builder", createManageMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: manage } # The alias is what is used to retrieve the menu

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
