<?php

namespace US\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
  public function findNews()
  {
    $query = $this->createQueryBuilder('n')
      ->leftJoin('n.image', 'i')
      ->addSelect('i')
      ->getQuery()
    ;

    return $query->getResult();
  }

  public function findSingleNews($idNews)
  {
    $query = $this->createQueryBuilder('n')
      ->leftJoin('n.image', 'i')
      ->addSelect('i')
      ->where('n.id = :n_id')
        ->setParameter('n_id', $idNews)
      ->getQuery()
    ;

    return $query
            ->getSingleResult();
    ;
  }

  public function findSingleNewsWithSlug($slugNews)
  {
    $query = $this->createQueryBuilder('n')
      ->leftJoin('n.image', 'i')
      ->addSelect('i')
      ->where('n.slug = :n_slug')
        ->setParameter('n_slug', $slugNews)
      ->getQuery()
    ;

    return $query
            ->getSingleResult();
    ;
  }

  public function getNews()
  {

    $query = $this->createQueryBuilder('n')
    ->leftJoin('n.image', 'i')
    ->addSelect('i')
    ->orderBy('n.id', 'DESC')
    ->getQuery();

    $query->setMaxResults(5);

    return new Paginator($query);
  }

}
