<?php

namespace Proxies\__CG__\US\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \US\CoreBundle\Entity\Image implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'id', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'name', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'ext', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'alt', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'oldName', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'products', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'news', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'categories', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'file', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'oldNameFile', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'tempFilename');
        }

        return array('__isInitialized__', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'id', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'name', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'ext', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'alt', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'oldName', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'products', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'news', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'categories', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'file', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'oldNameFile', '' . "\0" . 'US\\CoreBundle\\Entity\\Image' . "\0" . 'tempFilename');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Image $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldName($oldName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldName', array($oldName));

        return parent::setOldName($oldName);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldName', array());

        return parent::getOldName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldFileName($oldFileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldFileName', array($oldFileName));

        return parent::setOldFileName($oldFileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldFileName', array());

        return parent::getOldFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setExt($ext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExt', array($ext));

        return parent::setExt($ext);
    }

    /**
     * {@inheritDoc}
     */
    public function getExt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExt', array());

        return parent::getExt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlt($alt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlt', array($alt));

        return parent::setAlt($alt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlt', array());

        return parent::getAlt();
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\US\CatalogBundle\Entity\Product $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', array($product));

        return parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\US\CatalogBundle\Entity\Product $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', array($product));

        return parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addNews(\US\NewsBundle\Entity\News $news)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNews', array($news));

        return parent::addNews($news);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNews(\US\NewsBundle\Entity\News $news)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNews', array($news));

        return parent::removeNews($news);
    }

    /**
     * {@inheritDoc}
     */
    public function getNews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNews', array());

        return parent::getNews();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function preRemoveUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preRemoveUpload', array());

        return parent::preRemoveUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

}
